# Install script for directory: C:/work/BookInven/lib/opencv/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/work/BookInven/lib/opencv_mybuild/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xdevx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x86/vc15/staticlib" TYPE STATIC_LIBRARY FILES "C:/work/BookInven/lib/opencv_mybuild/lib/Debug/ade.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/x86/vc15/staticlib" TYPE STATIC_LIBRARY FILES "C:/work/BookInven/lib/opencv_mybuild/lib/Release/ade.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xlicensesx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/etc/licenses" TYPE FILE OPTIONAL RENAME "ade-LICENSE" FILES "C:/work/BookInven/lib/opencv_mybuild/3rdparty/ade/ade-0.1.1d/LICENSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/calib3d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/core/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/dnn/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/features2d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/flann/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/gapi/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/highgui/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/imgproc/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/java/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/js/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/ml/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/objdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/photo/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/python/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/stitching/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/ts/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/video/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/videoio/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/world/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/aruco/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/bgsegm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/bioinspired/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/ccalib/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cnn_3dobj/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cudev/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/cvv/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/datasets/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/dnn_objdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/dpm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/face/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/freetype/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/fuzzy/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/hdf/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/hfs/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/img_hash/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/line_descriptor/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/matlab/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/optflow/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/ovis/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/phase_unwrapping/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/plot/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/reg/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/rgbd/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/saliency/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/sfm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/shape/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/stereo/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/structured_light/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/superres/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/surface_matching/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/text/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/tracking/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/videostab/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/viz/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/xfeatures2d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/ximgproc/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/xobjdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/.firstpass/xphoto/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/core/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/flann/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/imgproc/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/java_bindings_generator/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/ml/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/phase_unwrapping/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/photo/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/plot/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/reg/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/surface_matching/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/xphoto/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/dnn/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/freetype/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/fuzzy/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/gapi/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/hfs/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/img_hash/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/imgcodecs/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/videoio/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/highgui/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/ts/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/bioinspired/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/dnn_objdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/features2d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/line_descriptor/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/saliency/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/text/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/calib3d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/ccalib/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/datasets/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/objdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/rgbd/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/shape/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/stereo/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/structured_light/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/video/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/videostab/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/xfeatures2d/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/ximgproc/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/xobjdetect/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/aruco/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/bgsegm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/dpm/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/face/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/optflow/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/stitching/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/superres/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/tracking/cmake_install.cmake")
  include("C:/work/BookInven/lib/opencv_mybuild/modules/python_bindings_generator/cmake_install.cmake")

endif()

